#+TITLE: Foraminifera Census Data Compilation in the Last Glacial Maximum (21 ka)

 [[https://img.shields.io/badge/License-CC_BY--NC_4.0-lightgrey.svg]]

* About

This project aims to collect and sort out existing foraminifera census data in the Last Glacial Maximum (21 ka). These data, as those of pre-industrial project, will be used to construct foraminifera thermal performance curves. 
+ Author: Rui Ying (rui.ying@bristol.ac.uk)
+ Publication citation: Ying, R., Monteiro, F. M., Wilson, J. D., & Schmidt, D. N. (2023). in submission

* Structure
+ /raw: raw data after cleaning
+ /fg: functionl group level data in each project
+ /sp: species level data in each project
+ /tidy: combined lgm and forcens in fg/sp or absolute/relative abundance. SST are assigned according to the georeferences.

* Raw Data Sources
** [[file:raw/RAEDME.txt][Foraminifera global abundance]]
** LGM Sea Surface Temperature

Tierney, J. E., Zhu, J., King, J., Malevich, S. B., Hakim, G. J., & Poulsen, C. J. (2020). Glacial cooling and climate sensitivity revisited. Nature, 584(7822), 569-573.

** Pre-industrial Sea Surface Temperature
Kennedy, J. J., Rayner, N. A., Atkinson, C. P., & Killick, R. E. (2019). An ensemble data set of sea‐surface temperature change from 1850: the Met Office Hadley Centre HadSST.4.0.0.0 data set. Journal of Geophysical Research: Atmospheres, 124.

* Data cleaning
** Conceptual Steps
+ 0 read raw data in wide format
+ 1 clean and replace column name
+ 2 generate species-based relative/absolute abundance (long format, in `sp` folder)
+ 3 generate functional group-based relative/absolute abundance (long format, in `fg` folder)
+ 4 merge all data in lgm in long format and convert to wide format (in `tidy` folder, sp in abbreviation)
+ 5 Add SST in each lgm data

#+BEGIN_QUOTE
Taxonomy in this project is as Brummer and Kucera (2022). And relative abundance is in decimal format (0-1) not percentage.
#+END_QUOTE
** Run the codes
+ Open foram_core.Rproject and follow the prompt

* License
This project is under protection of Attribution-NonCommercial 4.0 International (CC BY NC 4.0) license, which means you can share and adapt the code but you also must give appropriate credit to this project.
