
## replace
climap <- climap %>% mutate(Species=recode(Species, 
                                           "N. pachyderma d" =  "N. pachyderma",
                                           "G. pachyderma" = "N. pachyderma",
                                           "G. ruber (sum of G. ruber pink and G. r...)" ="G. ruber",
                                           "G. anfracta" = "D. anfracta",
                                           "N. pachyderma s" = "N. incompta",
                                           "G. ruber w" = "G. ruber",
                                           "G. ruber p" = "G. ruber",
                                           "G. ruber hsp" = "G. ruber",
                                           "G. quinqueloba d"= "T. quinqueloba",
                                           "G. quinqueloba" = "T. quinqueloba",
                                           "G. quinqueloba s" =  "T. quinqueloba",
                                           "G. truncatulinoides s" = "G. truncatulinoides",
                                           "G. truncatulinoides d" = "G. truncatulinoides",                                           
                                           "G. trilobus sac" = "G. sacculifer",
                                           "G. sacculifer sac" = "G. sacculifer",
                                           "G. sacculifer wo sac" = "G. sacculifer",
                                           "G. humilis" = "T. humilis",
                                           "G. hexagona" = "G. hexagonus",
                                           "G. sacculifer (sum of G. sacculifer no sac a...)" = "G. sacculifer",
                                           "G. tumida flexuosa" = "G. tumida",
                                           "G. pumilio"= "B. pumilio",
                                           "G. iota" = "T. iota",
                                           "G. dutertrei" ="N. dutertrei",
                                           "G. trilobus tril" = "G. clavaticamerata",
                                           "G. menardii (sum of G. menardii, G. tumida...)"="G. menardii",
                                           "G. bradyi" = "G. uvula",
                                           "Foram plankt oth" = "O. NA"
))