#+TITLE: Foraminifer census data source

* Foraminifera projects
** 1. surface sediment (pre-industrial)
+ ForCenS includes all the modern subset of CLIMAP, MARGO, GLAMAP and BUFD (Brown University Foraminiferal Database)

** 2. LGM downcore
+ CLIMAP (1970s, contains both 18ka and 120 ka, yielding a result that low-latitude have little change of SST in LGM)
+ MIX1999 (Mix et al. 1999 Palaeoceanography, a subset of CLIMAP data [CLIMAP-OSU] for revised transfer function)
+ MARGO (Launched in 2002, includes both Modern and LGM. Kucera 2005 QSR, MARGO project member. 2009 Nat Geo)
+ EPILOG (An update on CLIMAP,  South Atlantic only, e.g., age model, 1999. Mix et al. 2001 QSR)
+ GLAMAP (aka ATL947, Similar to EPILOG, but just for Atlantic and different time slices)
+ Manually checked sediment cores

* Data format  
+ ForCenS (relative + absolute abundance)
+ MARGO (relative + absolute abundance)
+ CLIMAP (relative + absolute abundance)
+ EPILOG (relative + absolute abundance)
+ GLAMAP (relative abundance only)
+ Mix1999 (relative abundance only)
+ Manually checked cores (only export absolute abundance)

* Raw data sources
** [[https://doi.org/10.1594/PANGAEA.873570][ForCenS/Modern]]
** [[https://doi.org/10.1594/PANGAEA.61208][CLIMA/LGM]]
** [[https://doi.org/10.1594/PANGAEA.57027][EPILOG/LGM]]
** [[https://doi.org/10.1594/PANGAEA.55156][GLAMAP/LGM]]
** [[https://doi.pangaea.de/10.1594/PANGAEA.61208][Mix1999/LGM]]

** MARGO
*** [[https://doi.org/10.1594/PANGAEA.227329][LGM Atlantic]] 
*** [[https://doi.org/10.1594/PANGAEA.227327][LGM Pacific]]
*** [[https://doi.org/10.1594/PANGAEA.227306][LGM Mediterranean]]
*** [[https://doi.org/10.1594/PANGAEA.227319][LGM Indo-Pacific]]

* Collecting strategies
Most sediment cores report relative abundance. I use two strategies to collect the absolute abundance data:
+ Strategy A: find cores with absolute abundance data in PANGAEA (e.g., CLIMAP project) and then search related age model
+ Strategy B: find age model or relative abundance data compilation with age models and then search absolute abundance
